# Copyright Gen Digital Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: app
description: Reference app to demonstrate TrustBloc Wallet SDK features
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <=3.7.2'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  qr_flutter: ^4.1.0
  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^8.1.0
  uuid: ^4.5.1
  shared_preferences: ^2.0.15
  intl: ^0.19.0
  uni_links: ^0.5.1
  safe_device: ^1.1.2
  cached_network_image: ^3.3.0
  jwt_decode: ^0.3.1
  url_launcher: ^6.1.11
  http: ^1.2.2
  js: ^0.6.4
  flutter_svg: ^2.0.9
  mobile_scanner: ^5.1.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  mockito: ^5.4.5             # Added for mocking
  build_runner: ^2.4.6        # Added for code generation

flutter_launcher_name:
  name: "TrustBloc"

flutter_launcher_icons:
  image_path: "images/appicon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo.png
    - lib/assets/images/background.png
    - lib/assets/images/glow.png
    - lib/assets/images/genericCredential.png
    - lib/assets/images/verified.png
    - lib/assets/images/credLogo.png
    - lib/assets/images/errorVector.png
    - lib/assets/images/success.png
    - lib/assets/images/logoIcon.png
    - lib/assets/images/error_icon.svg
    - lib/assets/images/tick-checked.svg
    - lib/assets/