// Objective-C API for talking to github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/did/creator Go package.
//   gobind -lang=objc github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/did/creator
//
// File is generated by gobind. Do not edit.

#ifndef __Creator_H__
#define __Creator_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Api.objc.h"

@class CreatorDIDCreator;

/**
 * DIDCreator is used for creating DID Documents using supported DID methods (currently only did:key).
 */
@interface CreatorDIDCreator : NSObject <goSeqRefInterface, ApiDIDCreator> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewDIDCreator returns a new DIDCreator.
keyHandleReader is optional. If provided, then it will be used to fetch a key (based on the KeyID in the options)
in the Create method. If not provided, then a new key will be generated and used for DID creation.
 */
- (nullable instancetype)init:(id<ApiKeyHandleReader> _Nullable)keyHandleReader;
/**
 * Create creates a DID document for the given DID method.
The usage of createDIDOpts depends on the DID method you're using.
 */
- (NSData* _Nullable)create:(NSString* _Nullable)method createDIDOpts:(ApiCreateDIDOpts* _Nullable)createDIDOpts error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * DIDMethodKey is the name used by the Create method for the did:key method.
 */
FOUNDATION_EXPORT NSString* _Nonnull const CreatorDIDMethodKey;

/**
 * NewDIDCreator returns a new DIDCreator.
keyHandleReader is optional. If provided, then it will be used to fetch a key (based on the KeyID in the options)
in the Create method. If not provided, then a new key will be generated and used for DID creation.
 */
FOUNDATION_EXPORT CreatorDIDCreator* _Nullable CreatorNewDIDCreator(id<ApiKeyHandleReader> _Nullable keyHandleReader);

#endif
