// Objective-C API for talking to github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/credentialsigner Go package.
//   gobind -lang=objc github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/credentialsigner
//
// File is generated by gobind. Do not edit.

#ifndef __Credentialsigner_H__
#define __Credentialsigner_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Api.objc.h"

@class CredentialsignerSigner;

/**
 * Signer is used to do credential signing operations.
 */
@interface CredentialsignerSigner : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewSigner returns a new Signer instance.
 */
- (nullable instancetype)init:(id<ApiKeyHandleReader> _Nullable)keyHandleReader didResolver:(id<ApiDIDResolver> _Nullable)didResolver credentialReader:(id<ApiCredentialReader> _Nullable)credentialReader crypto:(id<ApiCrypto> _Nullable)crypto;
/**
 * Derive does something (TODO: Implement).
credential must be a valid marshalled VC in JSON form.
Returns a credential.
 */
- (NSData* _Nullable)derive:(NSData* _Nullable)credential id_:(NSString* _Nullable)id_ jsonFrame:(NSData* _Nullable)jsonFrame nonce:(NSString* _Nullable)nonce error:(NSError* _Nullable* _Nullable)error;
/**
 * Issue issues a credential.
credential must be a valid marshalled VC in JSON form.
TODO: Format of proofOpts to be determined.
Returns a credential.
 */
- (NSData* _Nullable)issue:(NSData* _Nullable)credential id_:(NSString* _Nullable)id_ proofOpts:(NSString* _Nullable)proofOpts error:(NSError* _Nullable* _Nullable)error;
/**
 * Prove does something (TODO: Implement).
credentials must be valid marshalled VCs in a JSON array.
ids must be a JSON array.
presentation must be a valid marshalled presentation in JSON form.
TODO: Format of proofOpts to be determined.
Returns a presentation.
 */
- (NSData* _Nullable)prove:(NSData* _Nullable)credentials ids:(NSData* _Nullable)ids presentation:(NSData* _Nullable)presentation proofOpts:(NSString* _Nullable)proofOpts error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * NewSigner returns a new Signer instance.
 */
FOUNDATION_EXPORT CredentialsignerSigner* _Nullable CredentialsignerNewSigner(id<ApiKeyHandleReader> _Nullable keyHandleReader, id<ApiDIDResolver> _Nullable didResolver, id<ApiCredentialReader> _Nullable credentialReader, id<ApiCrypto> _Nullable crypto);

#endif
