// Objective-C API for talking to github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/openid4vp Go package.
//   gobind -lang=objc github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/openid4vp
//
// File is generated by gobind. Do not edit.

#ifndef __Openid4vp_H__
#define __Openid4vp_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Api.objc.h"
#include "Linkeddomains.objc.h"

@class Openid4vpInstance;

/**
 * Instance is used to help with OpenID4VP operations (TODO: Implement).
 */
@interface Openid4vpInstance : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
// skipped constructor Instance.NewInstance with unsupported parameter or return types

/**
 * GetQuery does something (TODO: Implement).
 */
- (NSData* _Nullable)getQuery:(NSError* _Nullable* _Nullable)error;
/**
 * PresentCredential does something (TODO: Implement).
 */
- (BOOL)presentCredential:(NSData* _Nullable)presentation kid:(NSString* _Nullable)kid error:(NSError* _Nullable* _Nullable)error;
@end

// skipped function NewInstance with unsupported parameter or return types


#endif
