
// Objective-C API for talking to the following Go packages
//
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/api
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/credentialinquirer
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/credentialschema
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/credentialsigner
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/credentialverifier
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/kms
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/linkeddomains
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/openid4ci
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/openid4vp
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/presentationexchange
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/storage
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/vdr
//	github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/wallethandle
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Walletsdk_FRAMEWORK_H__
#define __Walletsdk_FRAMEWORK_H__

#include "Api.objc.h"
#include "Credentialinquirer.objc.h"
#include "Credentialschema.objc.h"
#include "Credentialsigner.objc.h"
#include "Credentialverifier.objc.h"
#include "Kms.objc.h"
#include "Linkeddomains.objc.h"
#include "Openid4ci.objc.h"
#include "Openid4vp.objc.h"
#include "Presentationexchange.objc.h"
#include "Storage.objc.h"
#include "Vdr.objc.h"
#include "Wallethandle.objc.h"
#include "Universe.objc.h"

#endif
