// Objective-C API for talking to github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/vdr Go package.
//   gobind -lang=objc github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/vdr
//
// File is generated by gobind. Do not edit.

#ifndef __Vdr_H__
#define __Vdr_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class VdrVerifiableDataRegistry;

/**
 * VerifiableDataRegistry performs VDR operations.
 */
@interface VdrVerifiableDataRegistry : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
/**
 * Create does something // TODO: Complete this.
 */
- (NSData* _Nullable)create:(NSData* _Nullable)didDocument error:(NSError* _Nullable* _Nullable)error;
/**
 * Resolve does something // TODO: Complete this.
 */
- (NSData* _Nullable)resolve:(NSString* _Nullable)did error:(NSError* _Nullable* _Nullable)error;
@end

#endif
