// Objective-C API for talking to github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/linkeddomains Go package.
//   gobind -lang=objc github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/linkeddomains
//
// File is generated by gobind. Do not edit.

#ifndef __Linkeddomains_H__
#define __Linkeddomains_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class LinkeddomainsLD;

/**
 * LD represents a type that can help with linked domains. TODO: Implement.
 */
@interface LinkeddomainsLD : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewLD returns a new LD instance. TODO: Implement.
 */
- (nullable instancetype)init;
@end

/**
 * NewLD returns a new LD instance. TODO: Implement.
 */
FOUNDATION_EXPORT LinkeddomainsLD* _Nullable LinkeddomainsNewLD(void);

#endif
