// Objective-C API for talking to github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/storage Go package.
//   gobind -lang=objc github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/storage
//
// File is generated by gobind. Do not edit.

#ifndef __Storage_H__
#define __Storage_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class StorageProvider;

/**
 * A Provider allows for credential storage and retrieval.
 */
@interface StorageProvider : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewProvider returns a new Provider.
 */
- (nullable instancetype)init;
/**
 * Add stores the given credential.
 */
- (BOOL)add:(NSData* _Nullable)vc error:(NSError* _Nullable* _Nullable)error;
/**
 * Get returns a credential with the given id. An error is returned if no credential exists with the given id.
 */
- (NSData* _Nullable)get:(NSString* _Nullable)id_ error:(NSError* _Nullable* _Nullable)error;
/**
 * GetAll returns all stored credentials.
 */
- (NSData* _Nullable)getAll:(NSError* _Nullable* _Nullable)error;
/**
 * Remove removes the credential with the matching id, if it exists.
 */
- (BOOL)remove:(NSString* _Nullable)id_ error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * NewProvider returns a new Provider.
 */
FOUNDATION_EXPORT StorageProvider* _Nullable StorageNewProvider(void);

#endif
