// Objective-C API for talking to github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/wallethandle Go package.
//   gobind -lang=objc github.com/trustbloc/wallet-sdk/cmd/wallet-sdk-gomobile/wallethandle
//
// File is generated by gobind. Do not edit.

#ifndef __Wallethandle_H__
#define __Wallethandle_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Api.objc.h"

@class WallethandleHandle;

/**
 * A Handle exposes wallet import and export functionality.
 */
@interface WallethandleHandle : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewHandle returns a new Handle instance.
 */
- (nullable instancetype)init:(id<ApiCredentialReader> _Nullable)credentialReader credentialWriter:(id<ApiCredentialWriter> _Nullable)credentialWriter crypto:(id<ApiCrypto> _Nullable)crypto;
/**
 * Export returns all credentials stored in this wallet.
 */
- (NSData* _Nullable)export:(NSError* _Nullable* _Nullable)error;
/**
 * Import imports the given credentials into the wallet.
The credentials are expected to be a JSON array.
 */
- (BOOL)import:(NSData* _Nullable)credentials error:(NSError* _Nullable* _Nullable)error;
@end

/**
 * NewHandle returns a new Handle instance.
 */
FOUNDATION_EXPORT WallethandleHandle* _Nullable WallethandleNewHandle(id<ApiCredentialReader> _Nullable credentialReader, id<ApiCredentialWriter> _Nullable credentialWriter, id<ApiCrypto> _Nullable crypto);

#endif
